apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-guidetypescript-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-guidetypescript
  template:
    metadata:
      labels:
        app: api-guidetypescript
    spec:
      automountServiceAccountToken: false
      containers:
      - name: api-guidetypescript
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "1"
            memory: "512Mi"
            ephemeral-storage: "2Gi"
        image: edieveg316/api-guidetypescript-app:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
