apiVersion: v1
kind: Service
metadata:
  name: api-guidetypescript-service
spec:
  selector:
    app: api-guidetypescript
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer
