services:
  app:
    container_name: api-guidetypescript
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run start:prod
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
