services:
  app:
    container_name: api-guidetypescript
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run start:prod
