# ⚠️ OBSOLETO - Este workflow ha sido reemplazado por build.yml
# Este archivo se mantiene solo por compatibilidad histórica
# Todas las funcionalidades han sido consolidadas en build.yml con mejoras

# This is a basic workflow to help you get started with Actions

name: Build-test -dev (OBSOLETO)

# Controls when the workflow will run
on:
    # Deshabilitado - usar build.yml en su lugar
    workflow_dispatch:
        inputs:
            force_run:
                description: 'Forzar ejecución (no recomendado - usar build.yml)'
                required: false
                default: 'false'

jobs:
    build_test:
        runs-on: ubuntu-latest
        if: github.event.inputs.force_run == 'true'
        strategy:
            matrix:
                node-version: [18.x] # Actualizado a versión moderna
        steps:
            - uses: actions/checkout@v4 # Actualizado a v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4 # Actualizado a v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Aviso de workflow obsoleto
              run: |
                  echo "⚠️ AVISO: Este workflow está obsoleto"
                  echo "Por favor usa el workflow 'build.yml' que incluye todas las mejoras"
                  echo "Este workflow solo se ejecuta manualmente con force_run=true"
            - name: npm ci, build and test
              run: |
                  npm ci
                  npm run build --if-present
                  npm run test:ci
