name: 'Build, Test and Deploy'

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
    workflow_dispatch:

# Cancelar ejecuciones previas en la misma rama para ahorrar recursos
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    NODE_VERSION: '18.x'
    CI: true

jobs:
    test-and-build:
        name: Test, Lint and Build
        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:6.0
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Type check
              run: npm run type-check

            - name: Lint code
              run: npm run lint

            - name: Format check
              run: npm run format:check

            - name: Run tests
              run: npm run test:ci
              env:
                  NODE_ENV: test
                  MONGODB_URI: mongodb://localhost:27017/vegan-city-guide-test
                  JWT_SECRET: test-jwt-secret-key-for-github-actions

            - name: Build application
              run: npm run build

            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: dist/
                  retention-days: 7

            - name: Upload coverage reports
              uses: codecov/codecov-action@v4
              with:
                  file: ./coverage/lcov.info
                  flags: unittests
                  name: codecov-umbrella
              continue-on-error: true

    security:
        name: Security Audit
        runs-on: ubuntu-latest
        # Solo ejecutar auditoría en push a main para reducir tiempo
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci --omit=dev

            - name: Run security audit (Critical vulnerabilities)
              run: npm audit --audit-level critical --production

            - name: Run security audit (High vulnerabilities)
              run: npm audit --audit-level high --production
              continue-on-error: true

    # Job separado para deployment (si es necesario en el futuro)
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [test-and-build, security]
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-files
                  path: dist/

            - name: Deploy placeholder
              run: echo "Deployment step - configure according to your deployment strategy"
