name: "Build and GitFlow verification"

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - release/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Compile TypeScript code"
        run: npm install -g ts-node && ts-node src/server.ts
        env:
          PORT: ${{ secrets.PORT }}
          DB: ${{ secrets.DB }}

      - name: "Run unit tests"
        run: npm test

      - name: "Generate API build"
        run: npm install -g ts-node && ts-node src/server.ts
        env:
          PORT: ${{ secrets.PORT }}
          DB: ${{ secrets.DB }}

      - name: "Check current branch"
        run: |
          git branch | grep -E "feature|release|hotfix"
          if [ $? -eq 0 ]; then
            echo "Running on a development branch"
          else
            echo "Running on master branch"
          fi

      - name: "Check for changes in master branch"
        run: |
          git fetch origin master
          git diff origin/master..HEAD
          if [ $? -eq 0 ]; then
            echo "No changes in master branch"
          else
            echo "There are changes in master branch"
          fi

      - name: "Check for changes in develop branch"
        run: |
          git fetch origin develop
          git diff origin/develop..HEAD
          if [ $? -eq 0 ]; then
            echo "No changes in develop branch"
          else
            echo "There are changes in develop branch"
          fi

      - name: "Notify if there are errors"
        if: failure()
        run: |
          echo "Errors were found during compilation or testing"
          echo "Notify the development team"
